### ISSUE TITLE
⨯ Internal error: Error: Invariant failed: You should not use <Link> outside a <Router>

### ISSUE THREAD

**Issue by tynoschuck** [adrianhajdin/ecommerce#14]
Hello there!
I have this issue with the Nav Component.
When I run npm run dev I got a blank screen and the message above:
⨯ Internal error: Error: Invariant failed: You should not use <Link> outside a <Router>.
I know the problem is with the Button and the el property, cause when I remove it the code works but the button becames black.
Thank you in advance!

<img width="633" alt="Screenshot 2023-12-22 at 08 57 29" src="https://github.com/adrianhajdin/ecommerce/assets/58395745/5e0a071a-41f0-4bf9-b614-00cafab8b135">

**Comment by mdanish73** [comment]
Did you resolved this error?
